/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayerVideoIdRouteImport } from './routes/player.$videoId'
import { Route as DetailsVideoIdRouteImport } from './routes/details.$videoId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerVideoIdRoute = PlayerVideoIdRouteImport.update({
  id: '/player/$videoId',
  path: '/player/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsVideoIdRoute = DetailsVideoIdRouteImport.update({
  id: '/details/$videoId',
  path: '/details/$videoId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/details/$videoId': typeof DetailsVideoIdRoute
  '/player/$videoId': typeof PlayerVideoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/details/$videoId': typeof DetailsVideoIdRoute
  '/player/$videoId': typeof PlayerVideoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/details/$videoId': typeof DetailsVideoIdRoute
  '/player/$videoId': typeof PlayerVideoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/details/$videoId'
    | '/player/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/details/$videoId' | '/player/$videoId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/details/$videoId'
    | '/player/$videoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DetailsVideoIdRoute: typeof DetailsVideoIdRoute
  PlayerVideoIdRoute: typeof PlayerVideoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$videoId': {
      id: '/player/$videoId'
      path: '/player/$videoId'
      fullPath: '/player/$videoId'
      preLoaderRoute: typeof PlayerVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details/$videoId': {
      id: '/details/$videoId'
      path: '/details/$videoId'
      fullPath: '/details/$videoId'
      preLoaderRoute: typeof DetailsVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DetailsVideoIdRoute: DetailsVideoIdRoute,
  PlayerVideoIdRoute: PlayerVideoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
